/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackMan;

/**
 *
 * @author vojta3310
 */
public class GameGUI extends javax.swing.JFrame {
  private World mapa;
  /**
   * Creates new form GameGUI
   */
  public GameGUI(World map) {
    initComponents();
    mapa=map;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    canvas1 = new java.awt.Canvas();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        formPropertyChange(evt);
      }
    });
    addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        formKeyPressed(evt);
      }
    });

    canvas1.setBackground(new java.awt.Color(255, 255, 255));
    canvas1.setEnabled(false);
    canvas1.setMinimumSize(new java.awt.Dimension(500, 500));
    canvas1.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        canvas1KeyPressed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(0, 0, 0)
        .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(0, 0, 0))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(0, 0, 0))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void canvas1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_canvas1KeyPressed
    
  }//GEN-LAST:event_canvas1KeyPressed

  private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    
    switch (evt.getExtendedKeyCode()) {
      case 37 :  
        mapa.getPackman().moveRight();
      break;
      case 39:  
        mapa.getPackman().moveLeft();
      break;
      case 38:  
       mapa.getPackman().moveUp();
      break;
      case 40:  
        mapa.getPackman().moveDown();
      break;
      case 65 :  
        mapa.getMonster().moveRight();
      break;
      case 68:  
        mapa.getMonster().moveLeft();
      break;
      case 87:  
       mapa.getMonster().moveUp();
      break;
      case 83:  
        mapa.getMonster().moveDown();
      break;
    }
    
    mapa.paint(canvas1);
  }//GEN-LAST:event_formKeyPressed

  private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange

    //mapa.paint(canvas1);
  }//GEN-LAST:event_formPropertyChange



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.Canvas canvas1;
  // End of variables declaration//GEN-END:variables
}
